.github: Allow individual steps to fail
So we can show a pretty red X on the GUI, by returning error codes from
the bash methods, beyond the fail environment variable.

Signed-off-by: Jorge Marques <jorge.marques@analog.com>

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -7,6 +7,8 @@ on:
         required: true
         type: string
     outputs:
+      fatal:
+        value: ${{ jobs.checks.outputs.fatal}}
       fail:
         value: ${{ jobs.checks.outputs.fail }}
       warn:
@@ -16,8 +18,10 @@ jobs:
   checks:
     timeout-minutes: 7200
     runs-on: [self-hosted, v1]
+    continue-on-error: true
 
     outputs:
+      fatal: ${{ steps.assert.outputs.fatal }}
       fail: ${{ steps.assert.outputs.fail }}
       warn: ${{ steps.assert.outputs.warn }}
 
@@ -29,32 +33,45 @@ jobs:
         source ci/build.sh
         apply_prerun
 
+    - name: Assert state
+      if: ${{ failure() }}
+      run: |
+        source ci/build.sh
+        set_step_fail "assert_state"
+        echo "fatal=true" >> "$GITHUB_ENV"
+
     - name: License
+      if: ${{ !cancelled() && env.fatal != 'true' }}
       run: |
         source ci/build.sh
         check_license
 
     - name: Check patch
+      if: ${{ !cancelled() && env.fatal != 'true' }}
       run: |
         source ci/build.sh
         export -f check_checkpatch set_step_fail set_step_warn
-        timeout 1d bash -c "check_checkpatch" || \
-          echo "step_fail_checkpatch_timeout=true" >> "$GITHUB_ENV"
+        status=0; timeout 1d bash -c "check_checkpatch" || status=$?
+        [ $status -eq 124 ] && echo "step_fail_checkpatch_timeout=true" >> "$GITHUB_ENV"
+        exit $status
 
     - name: Coccicheck
+      if: ${{ !cancelled() && env.fatal != 'true' }}
       run: |
         source ci/build.sh
         export -f check_coccicheck set_step_fail set_step_warn
-        timeout 1d bash -c "check_coccicheck" || \
-          echo "step_fail_coccicheck_timeout=true" >> "$GITHUB_ENV"
+        status=0; timeout 1d bash -c "check_coccicheck" || status=$?
+        [ $status -eq 124 ] && echo "step_fail_coccicheck_timeout=true" >> "$GITHUB_ENV"
+        exit $status
 
     - name: CPP Check
+      if: ${{ !cancelled() && env.fatal != 'true' }}
       run: |
         source ci/build.sh
         check_cppcheck
 
     - name: Checkout and patch reference branch
-      if: ${{ !startsWith(github.base_ref, 'mirror/') && !startsWith(github.ref_name, 'mirror/') }}
+      if: ${{ !cancelled() && env.fatal != 'true' && !startsWith(github.base_ref, 'mirror/') && !startsWith(github.ref_name, 'mirror/') }}
       run: |
         git fetch origin --depth=1 "${{ inputs.ref_branch }}" &&
         git reset --hard origin/${{ inputs.ref_branch }} ||
@@ -90,18 +107,21 @@ jobs:
         done <<< "$files"
 
     - name: Check dt-bindings
+      if: ${{ !cancelled() && env.fatal != 'true' }}
       run: |
         source ci/build.sh
         check_dt_binding_check
 
     - name: Revert patch reference branch
-      if: ${{ !startsWith(github.base_ref, 'mirror/') && !startsWith(github.ref_name, 'mirror/') }}
+      if: ${{ !cancelled() && env.fatal != 'true' && !startsWith(github.base_ref, 'mirror/') && !startsWith(github.ref_name, 'mirror/') }}
       run: |
         git reset --hard $head_sha
 
-    - name: Assert checks
+    - name: Export labels
+      if: ${{ !cancelled() }}
       id: assert
       run: |
-        echo "warn=$(printenv | grep ^step_warn_ | grep -v =$ | tr '\n' ',' | sed 's/,$//')" >> "$GITHUB_OUTPUT"
-        echo "fail=$(printenv | grep ^step_fail_ | grep -v =$ | tr '\n' ',' | sed 's/,$//')" >> "$GITHUB_OUTPUT"
+        echo "fatal=$fatal" >> "$GITHUB_OUTPUT"
+        source ci/runner_env.sh
+        export_labels
 
